server:
  port: 0

spring:
  application:
    name: delivery
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/delivery
    username: delivery
    password: delivery

app:
  delivery:
    rates:
      base: 5.0
      address1: 1
      address2: 2
      fragile: 0.2
      weight: 0.3
      volume: 0.2
      street: 0.2

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE
  logbook:
    format:
      style: http