server:
  port: 0

spring:
  application:
    name: payment
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/payment
    username: payment
    password: payment

app:
  payment:
    vat-rate: 0.1

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE
  logbook:
    format:
      style: http