spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/analyzer
    username: analyzer
    password: analyzer

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

app:
  kafka:
    hub:
      consumer-topics: telemetry.hubs.v1
      bootstrap-server: localhost:9092
      group-id: hub.processor
    snapshot:
      consumer-topics: telemetry.snapshots.v1
      bootstrap-server: localhost:9092
      group-id: snapshot.processor